---
mde_installer_log: "/var/log/sa-mde-installer.log"
mde_installer_url: "https://raw.githubusercontent.com/microsoft/mdatp-xplat/refs/heads/master/linux/installation/mde_installer.sh"

# MSEdge configuration
edge_managed_policies:
  - key: BrowserSignin
    value: 1
  - key: ForceSync
    value: true
  - key: NonRemovableProfileEnabled
    value: true
  - key: PasswordManagerEnabled
    value: false
  - key: ManagedAccountsSigninRestriction
    value: "primary_account_strict"

edge_recommended_policies:
  - key: HubsSidebarEnabled
    value: false
